package com.payroll_app.project.enums;

public enum Department {
	 DEVELOPMENT, QA, DEVOPS, IT_SUPPORT, HR, SALES, MARKETING, FINANCE, PRODUCT, OPERATIONS,
	 UX_UI_DESIGN,RESEARCH_AND_DEVELOPMENT,TRAINING_AND_DEVELOPMENT,DATA_SCIENCE,CYBERSECURITY 

}
