package com.payroll_app.project.enums;

public enum Designation {
	INTERN, DEVELOPER, SENIOR_DEVELOPER, TECH_LEAD, ARCHITECT, ENGINEERING_MANAGER, 
	PROJECT_MANAGER, PRODUCT_MANAGER, TEAM_LEAD, QA_LEAD, DEVOPS_ENGINEER, CTO,
	DATA_ANALYST,DATA_ENGINEER,QA_AUTOMATION_ENGINEER,DEVOPS_ARCHITECT,INFRASTRUCTURE_ENGINEER

}
