package com.payroll_app.project.enums;

public enum ProjectType {
	BANKING,RETAIL,HEALTHCARE,EDUCATION,ECOMMERCE,TELECOMMUNICATION,SALES,
	CLOUD_COMPUTING,CYBERSECURITY,ARTIFICIAL_INTELLIGENCE,DATA_SCIENCE,BLOCKCHAIN
}
